# Source data
sourcedir: "/exports/sascstudent/dbayraktar/snakemake_pipeline_development/RPCA"

# FASTQ folder
readsdir: "data/reads"

# results are stored here
results: "results"

# Input genome
genome_fasta: "data/SIRV_150601a.fasta"

existing_annotation: "data/SIRV_isofroms.gtf"

# minimap2 parameters
minimap2_opts: "-uf -k14"

# threads
threads: 4