# Source data
sourcedir: "/exports/sascstudent/dbayraktar/snakemake_pipeline_development/RPCA"

# FASTQ folder
readsdir: "/exports/sascstudent/dbayraktar/Data/selas_data/filter"

# results are stored here
results: "results"

# Input genome
genome_fasta: "/exports/sascstudent/dbayraktar/Data/selas_data/WT_AdV-lumc007_WGS-headeredit.fa"

existing_annotation: "/exports/sascstudent/dbayraktar/Data/selas_data/AdV-lumc007_LUMC.gtf"

# minimap2 parameters
minimap2_opts: "-uf -k14"

# TALON parameters
mincounts: "5"

mindatasets: "2"

# FLAIR parameters

flair_correct_window: 10

flair_collapse_quality: 1

flair_abundance_quality: 1



# threads
threads: 10