# Source data
sourcedir: "/exports/sascstudent/dbayraktar/snakemake_pipeline_development/RPCA"

# FASTQ folder
readsdir: "/exports/sascstudent/dbayraktar/Data/selas_data/filter"

# results are stored here
results: "results"

# Input genome
genome_fasta: "/exports/sascstudent/dbayraktar/Data/selas_data/WT_AdV-lumc007_WGS-headeredit.fa"

existing_annotation: "/exports/sascstudent/dbayraktar/Data/selas_data/AdV-lumc007_LUMC.gtf"

# minimap2 parameters
minimap2_opts: "-uf -k14"

# TALON parameters
mincounts: "5"

mindatasets: "2"

# FLAIR parameters

flair_correct_window: 10

flair_collapse_quality: 1

flair_abundance_quality: 1

# OXFORD parameters

oxford_poly_context: 24

oxford_max_poly_run: 8

oxford_minimum_mapping_quality: 40

oxford_stringtie_opts: " --conservative "



# threads
threads: 10