# Source data
sourcedir: "/exports/sascstudent/dbayraktar/snakemake_pipeline_development/RPCA"

# FASTQ folder
readsdir: "/exports/sascstudent/dbayraktar/Data/selas_data/filter_pipeline"

# results are stored here
results: "results"

# run name
run_name: "oxford_avglen"

# Input genome
genome_fasta: "/exports/sascstudent/dbayraktar/Data/selas_data/WT_AdV-lumc007_WGS-headeredit.fa"

existing_annotation: "/exports/sascstudent/dbayraktar/Data/selas_data/AdV-lumc007_LUMC.gtf"

# minimap2 parameters
minimap2_opts: "-uf -k14"

minimap_index_opts: " -k14 "

# TALON parameters
talon_mincounts: "1"

talon_mindatasets: "1"

talon_5p: 500

talon_3p: 300

# FLAIR parameters

flair_correct_window: 10

flair_collapse_window: 100

flair_collapse_quality: 1

flair_collapse_support: 3

flair_collapse_max_ends: 2

flair_collapse_optional: " "

flair_abundance_quality: 1

# OXFORD parameters

oxford_poly_context: 24

oxford_max_poly_run: 8

oxford_minimum_mapping_quality: 40

oxford_stringtie_opts: " -c 1 -f 0.01 "

oxford_merge_opts: " -m 50 -c 0 -f 0.01 "

oxford_count_opts: " -L -p 10 "

# threads
threads: 10