# Source data
sourcedir: "/exports/sascstudent/dbayraktar/snakemake_pipeline_development/RPCA"

# FASTQ folder
readsdir: "data/SIRV_E0_PCS109_50.fq"

# results are stored here
results: "results"

# Input genome
genome_fasta: "data/SIRV_150601a.fasta"

existing_annotation: "data/SIRV_isofroms.gtf"
